/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-adipose.glb --output src/models/Adipose.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-adipose.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_subcutaneous_abdominal_adipose_tissue_LUQ_area.geometry} material={materials.VHM_adipose3} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_subcutaneous_abdominal_adipose_tissue_RUQ_area.geometry} material={materials.VHM_adipose2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_subcutaneous_abdominal_adipose_tissue_umbilicus_area.geometry} material={materials.VHM_adipose1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-adipose.glb')
