/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-blood-vasculature.glb --output src/models/BloodVasculature.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-blood-vasculature.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_superior_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_ophthalmic_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_central_retinal_vein_L.geometry} material={materials['eye_edits_012024:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_superior_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_ophthalmic_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_central_retinal_vein_R.geometry} material={materials['eye_edits_012022:pasted__vein_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_central_retinal_artery_L.geometry} material={materials['eye_edits_012024:pasted__artery_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_opthalmic_artery_L.geometry} material={materials['eye_edits_012024:pasted__artery_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_long_posterior_ciliary_artery_L.geometry} material={materials.pasted__pasted__dura_mater_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_central_retinal_artery_R.geometry} material={materials['eye_edits_012022:pasted__artery_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_opthalmic_artery_R.geometry} material={materials['eye_edits_012022:pasted__artery_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_long_posterior_ciliary_artery_R.geometry} material={materials.pasted__dura_mater_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_mesenteric_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_median_sacral_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sigmoid_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_superior_mesenteric_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_superior_rectal_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_pancreaticoduodenal_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_common_iliac_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_common_iliac_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_external_iliac_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_external_iliac_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_rectal_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_rectal_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_internal_pudendal_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_internal_pudendal_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_internal_iliac_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_internal_iliac_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_colic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ileocolic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_colic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_colic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_rectal_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_rectal_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_mesenteric_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_superior_mesenteric_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_marginal_artery_of_Drummond.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_colic_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_colic_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_colic_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ileocolic_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sigmoid_artery_a.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sigmoid_artery_b.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sigmoid_artery_c.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_renal_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_renal_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_aortic_arch.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ascending_aorta.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_brachiocephalic_artery_b.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_brachiocephalic_artery_a.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_common_carotid_artery_a.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_common_carotid_artery_b.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_subclavian_artery_a.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_subclavian_artery_b.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_descending_aorta_a.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_descending_aorta_b.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_anterior_descending_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_marginal_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posterior_descending_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_diagonal_branch_of_anterior_descending_branch_of_left_coronary_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_coronary_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_coronary_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_diagonal_branch_of_left_anterior_descending_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_marginal_branch.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_artery_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_artery_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_trunk.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_great_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_oblique_vein_of_left_atrium.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_anterior_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_coronary_sinus.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_posterior_vein_of_left_ventricle.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_small_cardiac_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_vein_R_inf.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_vein_R_sup.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_vein_L_inf.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_vein_L_sup.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_brachiocephalic_vein_L.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_brachiocephalic_vein_R.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_superior_vena_cava.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_vena_cava_b.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_inferior_vena_cava_a.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_splenic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_splenic_artery.geometry} material={materials.artery_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cystic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cystic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_celiac_trunk.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_proper_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_posterior_segmental_right_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_anterior_segmental_right_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_common_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_hepatic_artery_branch_of_left_hepatic_artery.geometry} material={materials.phong4} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_hepatic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_hepatic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_middle_hepatic_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_branch_of_portal_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_branch_of_portal_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_portal_vein.geometry} material={materials.vein_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hepatic_portal_vein.geometry} material={materials.vein_mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-blood-vasculature.glb')
