/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-eye-l.glb --output src/models/EyeLeft.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-eye-l.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_retina_L.geometry} material={materials.pasted__retina_mat}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_fovea_L.geometry} material={materials.pasted__fovea_mat} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_macula_lutea_L.geometry} material={materials.pasted__macula_mat} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_optic_disc_L.geometry} material={materials.pasted__retina_mat} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_vitreous_humor_L.geometry} material={materials['eye_edits_012042:humor_mat1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cornea_L.geometry} material={materials['eye_edits_012043:Cornea_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_bulbar_conjunctiva_L.geometry} material={materials['eye_edits_012043:Bone_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_iris_L.geometry} material={materials.pasted__iris_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_trabecular_meshwork_L.geometry} material={materials['eye_edits_012042:meniscus_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ciliary_body_L.geometry} material={materials['eye_edits_012042:lung_mat']}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_ciliary_muscle_L.geometry} material={materials['eye_edits_012042:lung_mat']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_aqueous_humor_L.geometry} material={materials.pasted__humours_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_schlemms_canal_L.geometry} material={materials['eye_edits_012042:Skin_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_lens_L.geometry} material={materials['eye_edits_012042:lens2']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_corneo_scleral_junction_L.geometry} material={materials['eye_edits_012042:limbus1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ora_serrata_of_retina_L.geometry} material={materials['eye_edits_012042:Ora_serrata_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_suspensory_ligament_of_lens_L.geometry} material={materials['eye_edits_012042:iris_mat1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ciliary_processes_L.geometry} material={materials['eye_edits_012042:brain_mat1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pupil_L.geometry} material={materials.pasted__pupil_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_optic_choroid_L.geometry} material={materials.pasted__choroid_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sclera_L.geometry} material={materials['eye_edits_012046:Eyeball_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_palpebral_conjunctiva_of_upper_eyelid_L.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_palpebral_conjunctiva_of_lower_eyelid_L.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat2} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-eye-l.glb')
