/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-eye-r.glb --output src/models/EyeRight.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-eye-r.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_retina_R.geometry} material={materials['eye_edits_012042:retina1']}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_fovea_R.geometry} material={materials['eye_edits_012043:fovea_mat']} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_macula_lutea_R.geometry} material={materials['eye_edits_012043:macula']} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_optic_disc_R.geometry} material={materials['eye_edits_012042:pasted__retina3']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sclera_R.geometry} material={materials['eye_edits_012042:Eyeball_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_optic_choroid_R.geometry} material={materials['eye_edits_012043:choroid_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pupil_R.geometry} material={materials['eye_edits_012042:pupil1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ciliary_processes_R.geometry} material={materials['eye_edits_012043:brain_mat1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_suspensory_ligament_of_lens_R.geometry} material={materials['eye_edits_012043:iris_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ora_serrata_of_retina_R.geometry} material={materials['eye_edits_012043:Ora_serrata_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_corneo_scleral_junction_R.geometry} material={materials['eye_edits_012043:limbus1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_lens_R.geometry} material={materials['eye_edits_012042:lens1']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_schlemms_canal_R.geometry} material={materials['eye_edits_012043:Skin_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_aqueous_humor_R.geometry} material={materials['eye_edits_012042:humor_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ciliary_body_R.geometry} material={materials['eye_edits_012044:lung_mat']}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_ciliary_muscle_R.geometry} material={materials['eye_edits_012045:lung_mat']} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_trabecular_meshwork_R.geometry} material={materials['eye_edits_012043:meniscus_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_iris_R.geometry} material={materials['eye_edits_012042:iris_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_bulbar_conjunctiva_R.geometry} material={materials['eye_edits_012042:Bone_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cornea_R.geometry} material={materials['eye_edits_012042:Cornea_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_vitreous_humor_R.geometry} material={materials['eye_edits_012042:humor_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_palpebral_conjunctiva_of_upper_eyelid_R.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_palpebral_conjunctiva_of_lower_eyelid_R.geometry} material={materials.pasted__pasted__pasted__pasted__conjunctiva_Mat1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-eye-r.glb')
