/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-heart.glb --output src/models/Heart.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-heart.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_mitral_valve.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_tricuspid_valve.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_aortic_valve.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pulmonary_valve.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_papillary_muscle_of_heart_anterior.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_papillary_muscle_of_heart_anterolateral.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_papillary_muscle_of_heart_medial.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_papillary_muscle_of_heart_posterior.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_papillary_muscle_of_heart_posteromedial.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_cardiac_atrium.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_cardiac_atrium.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_heart_right_ventricle.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_interventricular_septum.geometry} material={materials.heart_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_heart_left_ventricle.geometry} material={materials.heart_mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-heart.glb')
