/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-intervertebral-disk.glb --output src/models/IntervertebralDisk.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-intervertebral-disk.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_axis.geometry} material={materials.C3IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_third_cervical_vertebra.geometry} material={materials.C4IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_fourth_cervical_vertebra.geometry} material={materials.C5IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_fifth_cervical_vertebra.geometry} material={materials.C6IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_sixth_cervical_vertebra.geometry} material={materials.C7IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_seventh_cervical_vertebra.geometry} material={materials.T1IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_third_cervical_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_third_cervical_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_fourth_cervical_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_fourth_cervical_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_fifth_cervical_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_fifth_cervical_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_sixth_cervical_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_sixth_cervical_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_seventh_cervical_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_seventh_cervical_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_twelfth_thoracic_vertebra.geometry} material={materials.L1IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_eleventh_thoracic_vertebra.geometry} material={materials.T12IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_tenth_thoracic_vertebra.geometry} material={materials.T11IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_ninth_thoracic_vertebra.geometry} material={materials.T10IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_eighth_thoracic_vertebra.geometry} material={materials.T9IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_seventh_thoracic_vertebra.geometry} material={materials.T8IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_sixth_thoracic_vertebra.geometry} material={materials.T7IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_fifth_thoracic_vertebra.geometry} material={materials.T6IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_fourth_thoracic_vertebra.geometry} material={materials.T5IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_third_thoracic_vertebra.geometry} material={materials.T4IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_second_thoracic_vertebra.geometry} material={materials.T3IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_first_thoracic_vertebra.geometry} material={materials.T2IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_first_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_first_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_second_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_second_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_third_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_third_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_fourth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_fourth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_fifth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_fifth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_sixth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_sixth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_seventh_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_seventh_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_eighth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_eighth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_ninth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_ninth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_tenth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_tenth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_eleventh_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_eleventh_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_twelfth_thoracic_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_twelfth_thoracic_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_fourth_lumbar_vertebra.geometry} material={materials.L5IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_third_lumbar_vertebra.geometry} material={materials.L4IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_second_lumbar_vertebra.geometry} material={materials.L3IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_intervertebral_disk_of_first_lumbar_vertebra.geometry} material={materials.L2IntervertebralDisk} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_first_lumbar_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_first_lumbar_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_second_lumbar_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_second_lumbar_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_third_lumbar_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_third_lumbar_vertebra} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_nucleus_pulposus_of_intervertebral_disk_of_fourth_lumbar_vertebra.geometry} material={materials.Nucleus_pulposus_of_intervertebral_disk_of_fourth_lumbar_vertebra} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-intervertebral-disk.glb')
