/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-kidney-r.glb --output src/models/KidneyRight.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-kidney-r.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_kidney_capsule_R.geometry} material={materials.kidneycapsule_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_of_kidney_R.geometry} material={materials.kidneycapsule_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_j.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_i.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_h.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_g.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_f.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_e.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_d.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_c.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_b.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_R_a.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_a.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_b.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_c.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_d.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_e.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_f.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_g.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_h.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_i.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_j.geometry} material={materials.kidney_pyramids_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_column_R.geometry} material={materials.kidneycortex_medulla_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_outer_cortex_of_kidney_R.geometry} material={materials.kidneycortex_medulla_mat1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-kidney-r.glb')
