/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-kidney-l.glb --output src/models/KidneyLeft.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-kidney-l.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_kidney_capsule_L.geometry} material={materials.kidneycapsule_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_of_kidney_L.geometry} material={materials.kidneycapsule_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_column_L.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_outer_cortex_of_kidney_L.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_a.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_b.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_c.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_d.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_e.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_f.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_g.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_h.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_papilla_L_i.geometry} material={materials.kidneycortex_medulla_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_a.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_b.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_c.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_d.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_e.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_f.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_g.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_h.geometry} material={materials.kidney_pyramids_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pyramid_L_i.geometry} material={materials.kidney_pyramids_mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-kidney-l.glb')
