/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-knee-l.glb --output src/models/KneeLeft.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-knee-l.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_meniscus_L.geometry} material={materials.meniscus_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fibula_L.geometry} material={materials.Bone_Mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_femur_L.geometry} material={materials.Bone_Mat2}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_articular_cartilage_of_knee_L.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_intercondylar_fossa_L.geometry} material={materials.Bone_Mat2}>
          <mesh castShadow receiveShadow geometry={nodes.VH_M_anterior_cruciate_enthesis_L.geometry} material={materials.Bone_Mat2} />
          <mesh castShadow receiveShadow geometry={nodes.VH_M_posterior_cruciate_enthesis_L.geometry} material={materials.Bone_Mat2} />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_condyle_of_femur_frontal_L.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_condyle_of_femur_inf_L.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_condyle_of_femur_sup_L.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_epicondylar_enthesis_L.geometry} material={materials.Bone_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_perichondular_surface_L.geometry} material={materials.Bone_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_distal_most_point_of_medial_condyle_of_femur_L.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_condyle_of_left_femur_inf.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_condyle_of_left_femur_sup.geometry} material={materials.Cartilage_Mat3} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_epicondylar_enthesis_L.geometry} material={materials.Bone_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_perichondular_surface_L.geometry} material={materials.Bone_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_patellar_surface_L.geometry} material={materials.Cartilage_Mat3} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_tibia_L.geometry} material={materials.Bone_Mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_patella_L.geometry} material={materials.Bone_Mat2} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-knee-l.glb')
