/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-knee-r.glb --output src/models/KneeRight.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-knee-r.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_meniscus_R.geometry} material={materials.meniscus_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_tibia_R.geometry} material={materials.Bone_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fibula_R.geometry} material={materials.Bone_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_patella_R.geometry} material={materials.Bone_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_femur_R.geometry} material={materials.Bone_Mat1}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_articular_cartilage_of_knee_R.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_intercondylar_fossa_R.geometry} material={materials.Bone_Mat1}>
          <mesh castShadow receiveShadow geometry={nodes.VH_M_anterior_cruciate_enthesis_R.geometry} material={materials.Bone_Mat1} />
          <mesh castShadow receiveShadow geometry={nodes.VH_M_posterior_cruciate_enthesis_R.geometry} material={materials.Bone_Mat1} />
        </mesh>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_condyle_of_femur_frontal_R.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_condyle_of_femur_inf_R.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_condyle_of_femur_sup_R.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_epicondylar_enthesis_R.geometry} material={materials.Bone_Mat1} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_lateral_perichondular_surface_R.geometry} material={materials.Bone_Mat1} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_distal_most_point_of_medial_condyle_of_femur_R.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_condyle_of_right_femur_inf.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_condyle_of_right_femur_sup.geometry} material={materials.Cartilage_Mat2} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_epicondylar_enthesis_R.geometry} material={materials.Bone_Mat1} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_medial_perichondular_surface_R.geometry} material={materials.Bone_Mat1} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_patellar_surface_R.geometry} material={materials.Cartilage_Mat2} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d-vh-m-knee-r.glb')
