/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-sbu-m-large-intestine.glb --output src/models/LargeIntestine.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-sbu-m-large-intestine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ascending_colon.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_descending_colon.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hepatic_flexure_of_colon.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_rectum.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sigmoid_colon.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_splenic_flexure_of_colon.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_transverse_colon.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ileocecal_valve.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_caecum.geometry} material={materials.colon_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_vermiform_appendix.geometry} material={materials.colon_mat} />
    </group>
  )
}

useGLTF.preload('/3d-sbu-m-large-intestine.glb')
