/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-larynx.glb --output src/models/Larynx.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-larynx.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_epiglottic_cartilage.geometry} material={materials.Cartilage_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cricoid_cartilage.geometry} material={materials.Cartilage_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_thyroid_cartilage.geometry} material={materials.Cartilage_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_arytenoid_cartilage_R.geometry} material={materials.Cartilage_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_arytenoid_cartilage_L.geometry} material={materials.Cartilage_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_corniculate_cartilage_L.geometry} material={materials.Cartilage_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_corniculate_cartilage_R.geometry} material={materials.Cartilage_Mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-larynx.glb')
