/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-liver.glb --output src/models/Liver.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-liver.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_bare_area_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_liver_capsule.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_diaphragmatic_surface.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_suprarenal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_gastric_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_colic_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_esophageal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_duodenal_impression_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_porta_hepatis.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_caudate_lobe_of_liver.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posteroinferior_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posterosuperior_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_anterosuperior_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_anteroinferior_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_anterolateral_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_posterolateral_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_superiomedial_segment.geometry} material={materials.Liver_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_inferomedial_segment.geometry} material={materials.Liver_Mat}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_quadrate_lobe_of_liver.geometry} material={materials.Liver_Mat} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hepataduodenal_ligament.geometry} material={materials.Ligament_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ligamentum_venosum.geometry} material={materials.Ligament_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_round_ligament_of_liver.geometry} material={materials.Ligament_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_triangular_ligament_of_liver.geometry} material={materials.Ligament_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_falciform_ligament.geometry} material={materials.Ligament_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_coronary_ligament_of_liver.geometry} material={materials.Ligament_Mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-liver.glb')
