/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-lung.glb --output src/models/Lung.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-lung.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_L.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_upper_L.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lingula_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_posterior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_anterior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_apical_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lingula_inferior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_lower_L.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_anterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lateral_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_medial_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_posetrior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_R.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_lateral_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_medial_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_middle_R.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_lower_R.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_anterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_lateral_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_medial_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posterior_basal_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_superior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_apical_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posterior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_anterior_bronchopulmonary_segment.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_upper_R.geometry} material={materials.lung_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cartilage_of_the_lobar_bronchus_L.geometry} material={materials.VH_M_leftFBXASC032lobarFBXASC032bronchusFBXASC032bronchial_cartilage} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cartilage_of_the_tertiary_bronchus_L.geometry} material={materials.VH_M_leftFBXASC032tertiaryFBXASC032bronchial_cartilage} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_superior_lobar_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_inferior_lobar_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_superior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_posterior_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_medial_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_apical_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_anterior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lingular_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lingula_superior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lingula_inferior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_lateral_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_anterior_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cartilage_of_the_lobar_bronchus_R.geometry} material={materials.VH_M_rightFBXASC032lobarFBXASC032bronchial_cartilage2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_cartilage_of_the_tertiary_bronchus_R.geometry} material={materials.VH_M_rightFBXASC032tertiaryFBXASC032bronchial_cartilage1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_intermediate_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_middle_lobar_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_superior_lobar_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_anterior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_lateral_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_lateral_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_lower_lobar_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_medial_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_medial_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posterior_basal.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_posterior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_superior_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_apical_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_anterior_basal_bronchus.geometry} material={materials.mucosa_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_bronchus.geometry} material={materials.mucosa_mat1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-lung.glb')
