/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-main-bronchus.glb --output src/models/MainBronchus.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-main-bronchus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_left_main_bronchus.geometry} material={materials.mucosa_mat1}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_cartilage_of_the_main_bronchus_L.geometry} material={materials.VH_M_leftFBXASC032mainFBXASC032bronchusFBXASC032bronchial_cartilage} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_right_main_bronchus.geometry} material={materials.mucosa_mat1}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_cartilage_of_the_main_bronchus_R.geometry} material={materials.VH_M_rightFBXASC032mainFBXASC032bronchusFBXASC032bronchial_cartilage} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d-vh-m-main-bronchus.glb')
