/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-mouth.glb --output src/models/Mouth.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-mouth.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_mandible.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:pasted__Bone_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_buccal_mucosa.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:pasted__Skin_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_mouth_floor.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:eye_edits_012022:lung_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_submandibular_gland_R.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:Gland_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_submandibular_gland_L.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:Gland_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_parotid_gland_R.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:Gland_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_parotid_gland_L.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:Gland_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sublingual_gland_L.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:Gland_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sublingual_gland_R.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:Gland_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_frenulum_of_upper_lip.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:pasted__Skin_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_frenulum_of_lower_lip.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:pasted__Skin_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_gingiva_of_lower_jaw.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:eye_edits_012054:lung_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ginviva_of_upper_jaw.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:eye_edits_012054:lung_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_posterior_part_of_tongue.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:heart_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_dorsal_tongue.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:heart_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ventral_tongue.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:heart_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fungiform_papillae.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:heart_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_circumvallate_papillae.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:heart_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hard_palate.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:_oral_cavity:united_colors_3:eye_edits_012054:lung_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_mucosa_of_soft_palate.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:_oral_cavity:united_colors_3:eye_edits_012054:lung_mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_set_of_lower_jaw_teeth.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:eye_edits_012056:Eyeball_Mat']} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_set_of_upper_jaw_teeth.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:eye_edits_012056:Eyeball_Mat']} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-mouth.glb')
