/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-pancreas.glb --output src/models/Pancreas.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-pancreas.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_body_of_pancreas.geometry} material={materials.Gland_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_tail_of_pancreas.geometry} material={materials.Gland_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_head_of_pancreas.geometry} material={materials.Gland_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_neck_of_pancreas.geometry} material={materials.Gland_Mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_uncinate_process_of_the_pancreas.geometry} material={materials.Gland_Mat1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-pancreas.glb')
