/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-pelvis.glb --output src/models/Pelvis.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-pelvis.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sacrum.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_coccyx.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pubis_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pubis_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pubis_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_pubis_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ilium_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ilium_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ilium_spongy_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ilium_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ischium_compact_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ischium_compact_bone_R.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ischium_spongy_bone_L.geometry} material={materials.Bone_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ischium_spongy_bone_R.geometry} material={materials.Bone_Mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-pelvis.glb')
