/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-prostate.glb --output src/models/Prostate.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-prostate.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_seminal_vesicle.geometry} material={materials.genitalDuct_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ejaculatory_duct.geometry} material={materials.genitalDuct_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_vas_deferens_L.geometry} material={materials.genitalDuct_mat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_vas_deferens_R.geometry} material={materials.genitalDuct_mat} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_prostatic_utricle.geometry} material={materials.ureter_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_seminal_colliculus.geometry} material={materials.ureter_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_apex_of_prostate.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_base_of_prostate.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_prostate_duct_R.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_prostate_duct_L.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_peripheral_zone_of_prostate_R.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_peripheral_zone_of_prostate_L.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_transition_zone__of_prostate_L.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_transition_zone_of_prostate_R.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_central_zone_of_prostate_R.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_central_zone_of_prostate_L.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_anterior_fibromuscular_stroma_L.geometry} material={materials.Gland_Mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_anterior_fibromuscular_stroma_R.geometry} material={materials.Gland_Mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-prostate.glb')
