/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-renal-pelvis-r.glb --output src/models/RenalPelvisRight.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-renal-pelvis-r.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pelvis_R.geometry} material={materials.ureter_mat1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-renal-pelvis-r.glb')
