/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-skin.glb --output src/models/Skin.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-skin.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_skin.geometry} material={materials['VH_M_United_041725_new_attribute_new_organs_only:pasted__Skin_Mat1']} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-skin.glb')
