/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-small-intestine.glb --output src/models/SmallIntestine.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-small-intestine.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ileum.geometry} material={materials.sm_intestine}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_ileum_terminal.geometry} material={materials.sm_intestine} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_jejunum.geometry} material={materials.sm_intestine} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_duodenum_ascending.geometry} material={materials.sm_intestine} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_duodenum_descending.geometry} material={materials.sm_intestine} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_duodenum_horizonal.geometry} material={materials.sm_intestine} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_duodenum_superior.geometry} material={materials.sm_intestine}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_duodenal_ampulla.geometry} material={materials.sm_intestine} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sphincter_of_hepatopancreatic_ampulla.geometry} material={materials.sm_intestine} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_papilla_of_santorini.geometry} material={materials.sm_intestine} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-small-intestine.glb')
