/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-spinal-cord.glb --output src/models/SpinalCord.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-spinal-cord.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C1_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C2_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C3_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C4_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C5_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C6_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C7_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_C8_segment_of_cervical_spinal_cord.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_first_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_second_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_third_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fourth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fifth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_sixth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_seventh_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_eighth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ninth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_tenth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_eleventh_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_twelfth_thoracic_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_first_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_second_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_third_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fourth_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fifth_lumbar_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_first_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_second_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_third_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fourth_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fifth_sacral_spinal_cord_segment.geometry} material={materials.pasted__retina2} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-spinal-cord.glb')
