/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-spleen.glb --output src/models/Spleen.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-spleen.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_colic_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_diaphragmatic_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_gastric_surface_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_hilum_of_spleen.geometry} material={materials.spleen_mat} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_surface_of_spleen.geometry} material={materials.spleen_mat} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-spleen.glb')
