/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-thymus.glb --output src/models/Thymus.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-thymus.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_thymus_lobe_L.geometry} material={materials.Gland_Mat3} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_thymus_lobe_R.geometry} material={materials.Gland_Mat3} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-thymus.glb')
