/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-trachea.glb --output src/models/Trachea.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-trachea.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_trachea.geometry} material={materials.mucosa_mat}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_tracheal_cartilage.geometry} material={materials.Cartilage_Mat1} />
        <mesh castShadow receiveShadow geometry={nodes.VH_M_carina.geometry} material={materials.Cartilage_Mat1} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d-vh-m-trachea.glb')
