/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-ureter-l.glb --output src/models/UreterLeft.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-ureter-l.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pelvis_L.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ureter_L.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_major_calyx_L_a.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_major_calyx_L_b.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_major_calyx_L_c.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_a.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_b.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_c.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_d.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_e.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_f.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_g.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_h.geometry} material={materials.ureter_mat2} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_L_i.geometry} material={materials.ureter_mat2} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-ureter-l.glb')
