/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-ureter-r.glb --output src/models/UreterRight.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-ureter-r.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_renal_pelvis_R.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ureter_R.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_major_calyx_R_a.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_major_calyx_R_b.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_a.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_b.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_c.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_d.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_e.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_f.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_g.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_h.geometry} material={materials.ureter_mat1} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_minor_calyx_R_i.geometry} material={materials.ureter_mat1} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-ureter-r.glb')
