/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 /home/anubhavanand/Documents/3d human anatomy/3d-vh-m-urinary-bladder.glb --output src/models/UrinaryBladder.jsx --shadows 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d-vh-m-urinary-bladder.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_urinary_bladder_neck_smooth_muscle.geometry} material={materials.ureter_mat3} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fundus_of_urinary_bladder_dome.geometry} material={materials.ureter_mat3} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_fundus_of_urinary_bladder_base1.geometry} material={materials.ureter_mat3}>
        <mesh castShadow receiveShadow geometry={nodes.VH_M_trigone_of_urinary_bladder.geometry} material={materials.ureter_mat3} />
      </mesh>
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ureteral_orifice_R.geometry} material={materials.ureter_mat3} />
      <mesh castShadow receiveShadow geometry={nodes.VH_M_ureteral_orifice_L.geometry} material={materials.ureter_mat3} />
    </group>
  )
}

useGLTF.preload('/3d-vh-m-urinary-bladder.glb')
